"""STEP 08 — Aggregate all results into one summary + a figure.

Run:  python src/step08_aggregate.py

Collects every results/*.csv produced by steps 01-07 into results/SUMMARY.md
and a baselines bar chart, ready to fill the manuscript [RESULT] markers.
"""
import pandas as pd
from config import RESULTS

def try_read(name):
    p = RESULTS / name
    return pd.read_csv(p) if p.exists() else None

def main():
    parts = {
        "TEP class distribution": "tep_class_distribution.csv",
        "Baselines (classical/ML)": "baselines_metrics.csv",
        "Deep baselines": "deep_baselines_metrics.csv",
        "Imbalance (overall)": "imbalance_metrics.csv",
        "Imbalance (rare-fault recall)": "imbalance_rare_recall.csv",
        "Uncertainty + open-set": "uncertainty_openset_metrics.csv",
        "Sim->real (PRONTO)": "sim2real_metrics.csv",
        "Interpretability (global)": "interpretability_global_importance.csv",
        "Interpretability (per fault)": "interpretability_per_fault_top.csv",
        "Unified CNN (closed-set)": "unified_metrics.csv",
        "Unified CNN (FDR/FAR/delay)": "unified_detection.csv",
        "Unified CNN (open-set scores)": "unified_openset.csv",
        "Multi-seed (unified CNN)": "multiseed_summary.csv",
        "Ablation (focal/weights)": "ablation.csv",
        "Same CNN on real PRONTO": "cnn_pronto_metrics.csv",
        "Aux datasets (multi-seed)": "aux_multiseed.csv",
        "Literature comparison": "sota_comparison.csv",
    }
    lines = ["# PICUP-FDD — Results Summary\n",
             "_Auto-generated by step08. Values fill the manuscript [RESULT] markers._\n"]
    for title, fname in parts.items():
        df = try_read(fname)
        lines.append(f"\n## {title}\n")
        if df is None:
            lines.append("_(not produced yet)_\n")
        else:
            head = df.head(12)
            lines.append("```\n" + head.to_string(index=False) + "\n```\n")
    (RESULTS / "SUMMARY.md").write_text("\n".join(lines), encoding="utf-8")
    print("Wrote", RESULTS / "SUMMARY.md")

    # baseline chart if available
    b = try_read("baselines_metrics.csv")
    if b is not None:
        try:
            import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt
            plt.figure(figsize=(8, 4))
            plt.bar(b["model"], b["macro_f1"])
            plt.ylabel("macro-F1"); plt.title("TEP baselines"); plt.xticks(rotation=30, ha="right")
            plt.tight_layout(); plt.savefig(RESULTS / "baselines_macroF1.png", dpi=120)
            print("Wrote baselines_macroF1.png")
        except Exception as e:
            print("chart skipped:", e)
    print("STEP 08 done.")

if __name__ == "__main__":
    main()
